# Generated by Django 3.2 on 2023-05-24 16:56

import django.core.validators
from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Укажите логин', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(regex='^[\\w.@+-]+$'), reviews.validators.validate_username], verbose_name='Логин'),
        ),
    ]
