# Generated by Django 3.2 on 2023-05-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_genre_titles_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genres',
            name='slug',
            field=models.SlugField(),
        ),
    ]
