# Generated by Django 3.2 on 2023-05-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_Review6'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='title_id',
        ),
    ]
